# Generated by Django 4.2.7 on 2023-11-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_programmer',
        ),
    ]
