# Generated by Django 4.2.7 on 2023-11-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_programmer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
